language: python

env:
  global:
    - secure: "EMv5MA5Bp+s1onu2et7AweKoJdjlKs9UjQGKJtwAkQEUu+PqgnMaj2KJ7oKv9E/NsWEudQ2+axA7TZtBfIRh4U8RLa+gQzIaLFe2iVUc8+DhT/MIxU7yjpuFx0IgLqwJ8vom7ZuuEwf9M6Q54vmMXcVIMkp/bpP2nmYYkxvV7SniE9Tqfb5htS+gEiEvQW7UpmD9tLTl5CuwYcd2EyyjwephbA0wWLsXxD9BoztFzujGBXLl/stOz88RK06mif1QhDa595Rinu4Q5fzOog7SOgyV7W1Kn9RAFAXydiGTq/FjyQWudUQ4gjibwXf5HJ2rxdX60mQsNDDqhe2m8WcWTdD3AjsNPuB4Ah/xJXzjFqwKvn69/ayO3ArwtPhFuI27yTp4BtfXWfma5sZkBT6iADVdi2YTncRneDdODfx/PRMSqwlqGjxG+4ssMGu1fI5A0dckysygJVtNACg3ujG/wzaX9MxiXxVqkl57rwC01oI2damvaHtziVVEzgNMD/d9AuZjPVY059F+fatEQk+JUYkWpleM+oxgUWzku9utuDKtK701nNm8k0u2lMbCB6yGm1zVg0Gf1h+d8tUQoONxWD7x7KyvVDgCYYvL8Pl64HOGdZ35+OJ7RDYJ7d7wdAHctBhUMaCvgtqecbzDCLr+dTb/WM/LL51+j/3jn7KnZ10="

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: PIP=pip
  - os: osx
    language: generic
    env: PIP=pip2

script:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export PIP_INSTALL_OPTS="--user"
    export PATH="${PATH}:$(python -m site --user-base)/bin"
  else
    export PIP_INSTALL_OPTS=""
    export PATH="${PATH}:$(python -m site --user-base)/bin"
  fi

- echo "${PATH}"

- $PIP install ${PIP_INSTALL_OPTS} cibuildwheel==0.9.4
- $PIP install ${PIP_INSTALL_OPTS} twine

- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew cask uninstall --force oclint
    brew install gcc
  fi

- python setup_project.py

- |
  export pkgdir="$(cat meta_pkgdir.txt)"
  export gh_repo_name="$(cat meta_pkgname.txt)"
  export gh_repo_owner="$(cat meta_owner.txt)"
  export tag="$(cat meta_tag.txt)"
  export TWINE_USERNAME="$(cat meta_twine_user.txt)"
  export TWINE_REPOSITORY_URL="$(cat meta_twine_repo_url.txt)"

- |
  export CIBW_SKIP="$(cat meta_CIBW_SKIP.txt)"
  export CIBW_BEFORE_BUILD_LINUX="source pre_build_linux.sh"
  export CIBW_BEFORE_BUILD_MACOS="source pre_build_osx.sh"
  export CIBW_TEST_COMMAND="python -m viscid check"

- cd ${pkgdir}
- cibuildwheel

- ls -la ./wheelhouse

- twine upload wheelhouse/*.whl

- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    rm -rf dist/*
    pip install numpy==$(python numpy_version.py)
    python setup.py sdist
    twine upload dist/*.tar.gz
  fi
